### ISSUE TITLE
Invite link no longer active

### ISSUE THREAD

**Issue by code2exe** [hnginternship5/HNGInternship#1]
This is what I got after clicking on the invite link.
![2018-04-10 08_38_01-greenshot](https://user-images.githubusercontent.com/16284830/38542743-99156ab2-3c9a-11e8-872f-e769a416ac88.png)

**Comment by dennisotugo** [comment]
@ghettopoly Sorry about that, http://bit.ly/2GMavRV

**Comment by code2exe** [comment]
I’m sorry; it’s still giving the same error.

**Comment by dennisotugo** [comment]
@ghettopoly https://bit.ly/2Jv2VNj

**Comment by code2exe** [comment]
Thank you!! It worked.

**Comment by dennisotugo** [comment]
@ghettopoly If you need help getting up to speed there, let me know

**Comment by code2exe** [comment]
Yea! I'm trying to fill in my name in the spreadsheet but its requesting for me to get permission from the admin to access it.

**Comment by dennisotugo** [comment]
@code2exe HNG Internship 5 has begun and the invite link has been updated accordingly.

**Comment by code2exe** [comment]
Yea! I have joined in!
Thanks, Dennis
